# -*- coding: utf-8 -*-
# Привязка абзацев к фрагментам нормативов. Ссылки:
# P<n> Правилник 96/2023, Z<n> Закон; суффикс #a-b — строки статьи, ~фраза — абзац с фразой
# R~фраза RIBA, A~ ACE, C~ CKA, G~ брошюра BSR, T~текст — литерал
REFS = {
# ---------------- Сербия
('01-strategiya','rs'):[('Что это',0,['Z112']),('Что это',1,['Z113#0']),('Что это',2,['Z114#0']),
  ('Генеральный',0,['P14#0']),('Генеральный',1,['Z117#0']),('Генеральный',2,['P14#1']),('Документы',0,['Z131#0']),('Детализация',0,['P34#1'])],
('02-zadanie','rs'):[('Что это',0,['Z53a#0']),('Что это',1,['Z53#0']),('Порядок',0,['Z56#0']),('Порядок',1,['Z8đ#0']),('Исходные',0,['P22#0'])],
('03-koncepciya','rs'):[('Что это',0,['P15#0']),('Что это',1,['P15~sastavni deo lokacijskih']),('Состав',0,['P35#0']),('Состав',1,['P36#0-1']),('Состав',2,['P38#0']),('Состав',3,['P39#0']),('Состав',4,['P41#0']),
  ('Детализация',0,['P40#1']),('Детализация',1,['P40#2']),('Детализация',2,['P40~Grafički prilozi idejnog rešenja se izrađuju na geodetskoj podlozi']),('Оформление',0,['P31~tablicu maksimalne širine 18 cm'])],
('04-eskiz','rs'):[('Что это',0,['P16#0']),('Что это',1,['Z118#0-2']),('Состав',0,['P42#0-3']),('Состав',1,['P45#0']),('Состав',2,['P46#0']),('Состав',3,['P49#0']),
  ('Детализация',0,['P47#1']),('Детализация',1,['P47#2']),('Детализация',2,['P47#3']),('Детализация',3,['P48#0'])],
('06-proekt-razresheniya','rs'):[('Что это',0,['P17#0']),('Состав по',0,['P52#1']),('Состав по',1,['P52#2']),('Состав по',2,['P52#3']),('Состав по',3,['P52#4']),('Состав по',4,['P52~Izuzetno, za objekte iz člana 133']),('Состав по',5,['P26#1-11']),
  ('Главная',0,['P51#0-4']),('Главная',1,['P54#0-6']),('Главная',2,['P55#0-4']),('Главная',3,['P57#0-4']),
  ('Детализация',0,['P56#1']),('Детализация',1,['P56#2']),('Детализация',2,['P56#3']),('Детализация',3,['P56#5']),
  ('Для разрешения',0,['P33#3-7']),('Для разрешения',1,['P58#0']),('Форма',0,['P20#0'])],
('07-ekspertiza','rs'):[('Что это',0,['P79#0']),('Что это',1,['P79#3']),('Что проверяется',0,['P80#1']),('Что проверяется',1,['P80#2']),('Что проверяется',2,['P80#3']),('Что проверяется',3,['P80#4']),('Что проверяется',4,['P80#5']),
  ('Документы',0,['P83#0']),('Документы',1,['P86#0']),('Ревизия',0,['Z131#0']),('Отличие',0,['Z8đ#0'])],
('08-razreshenie','rs'):[('Что это',0,['Z135#0']),('Сроки',0,['Z8d~po zahtevu za izdavanje građevinske dozvole']),('Действие',0,['Z137#0']),('Действие',1,['Z138a#0-1']),('Действие',2,['Z140#0'])],
('09-rabochaya','rs'):[('Что это',0,['P18#0']),('Состав',0,['P61#0-4']),('Состав',1,['P64#0']),('Состав',2,['P65#0']),('Состав',3,['P67#0','P68#0']),('Состав',4,['P70#0']),
  ('Детализация',0,['P66#0-4']),('Детализация',1,['Z123~u fazama'])],
('10-stroitelstvo','rs'):[('Начало',0,['Z148#0-1']),('Начало',1,['Z149#0']),('Участники',0,['Z152#0']),('Участники',1,['Z153#0-1']),('Этапные',0,['Z8d~prijavi završetka izgradnje temelja'])],
('11-ispolnitelnaya','rs'):[('Что это',0,['P19#1','Z124#2']),('Состав',0,['P71~nije došlo do odstupanja']),('Состав',1,['P72#0']),('Состав',2,['P73#0']),('Состав',3,['P77#0']),('Состав',4,['P78#0']),('Контроль',0,['Z124~ne podleže'])],
('12-priemka-vvod','rs'):[('Что это',0,['Z154#0-1']),('Что это',1,['Z155#0']),('Разрешение',0,['Z158#1']),('Разрешение',1,['Z158~Uz zahtev za izdavanje upotrebne dozvole prilaže se'])],
('14-ekspluatatsiya','rs'):[('Что это',0,['Z159#0']),('Что это',1,['P19#0'])],

# ---------------- Англия
('01-strategiya','uk'):[('Что это',0,['R~Outcome: The best means of achieving the Client Requirements confirmed']),('Состав работ',0,['R~capturing them in a Business Case']),('Состав работ',1,['R~The Project Risks consider any circumstances']),('Состав работ',2,['R~carrying out Site Surveys and corresponding planning appraisals']),('Состав работ',3,['R~gleaning Feedback from previous similar projects']),('Состав работ',4,['R~high-level Spatial Requirements relevant to any option']),('Документы',0,['R~Project Strategies are a crucial component of any project']),('Кто',0,['R~Only the client team is involved at this stage'])],
('02-zadanie','uk'):[('Что это',0,['R~Outcome: Project Brief approved by the client']),('Состав работ',0,['R~The Project Brief will contain guidance on the Project Outcomes']),('Состав работ',1,['R~Feasibility Studies might be required']),('Состав работ',2,['R~Spatial Requirements do need to be tested against the Project Budget']),('Состав работ',3,['R~A comprehensive set of Site Information needs to be sourced']),('Состав работ',4,['R~A Project Execution Plan should be prepared']),('Состав работ',5,['R~A Responsibility Matrix also needs to be prepared']),('Важно',0,['R~Feasibility Studies are not part of the design process']),('Кто',0,['R~Stage 1 involves only the client team'])],
('03-koncepciya','uk'):[('Что это',0,['R~Outcome: Architectural Concept approved by the client']),('Состав работ',0,['R~Stage 2 sets the Architectural Concept for a project']),('Состав работ',1,['R~Regular Design Reviews are used to seek comments']),('Состав работ',2,['R~The client may seek pre-application Planning Advice']),('Состав работ',3,['R~A Stage 2 Design Programme must be prepared']),('Документы',0,['R~everything captured in a Stage Report']),('Детализация',0,['R~Although Stage 2 is more about rules of thumb'])],
('05-ago-agr','uk'):[('Planning permission',0,['T~Order 2015, art. 34|8 weeks beginning with the day immediately following that on which the application is received']),('Planning permission',1,['R~a Planning Application can be submitted']),('Planning permission',2,['T~BSR, The three gateways|On 1 August 2021, HSE became a statutory consultee for planning applications for high-rise residential buildings, a service known as Planning Gateway One (PGO).'])],
('06-proekt-razresheniya','uk'):[('Что это',0,['R~Outcome: Architectural and engineering information Spatially Coordinated']),('Состав работ',0,['R~Detailed Design Studies and Engineering Analysis are undertaken']),('Состав работ',1,['R~Design Studies should be aligned to Cost Exercises and the development of the Outline Specification']),('Состав работ',2,['R~a Building Regulations review undertaken']),('Состав работ',3,['R~a Planning Application can be submitted']),('Детализация',0,['R~Changes to the Architectural Concept, for whatever reason']),('Детализация',1,['R~Employer’s Requirements might be issued at the end of Stage']),('Градостроительный',0,['T~BSR, The three gateways|a fire statement for full planning applications must be provided'])],
('07-ekspertiza','uk'):[('Building Regulations: способы',0,['T~Building Regulations 2010, reg. 12|Building Notice']),('Building Regulations: способы',1,['T~Building Regulations 2010, reg. 12|Application for Building Control Approval with Full Plans']),('HRB: Gateway 2',0,['T~BSR, The three gateways|Developers cannot proceed with construction until BSR has approved the application.']),('HRB: Gateway 2',1,['T~BSR, The three gateways|In your application you will need to: provide a comprehensive outline of the work that will be carried out; information about the building itself and the people involved in the building, such as the client, principal contractor and principal designer; set out standard building information, such as the site location plan and boundaries, and a fire and emergency file; provide a construction control plan (setting out how building work will be managed to maintain building regulations compliance), and a building regulations compliance statement (including reasons for the approach adopted); provide a change control plan to show how any proposed changes will be considered; and where relevant, a partial completion strategy']),('HRB: Gateway 2',2,['T~BSR, The three gateways|A multi-disciplinary team (MDT) will be assigned to each submission, and this will include a Registered Building Inspector, and any other specialists required to assess a submission.'])],
('08-razreshenie','uk'):[('Что это',0,['R~A Building Regulations Application should be made during Stage 4']),('Building Regulations: порядок',0,['T~Building Regulations 2010, reg. 16|Not more than five days after the day on which work is to be regarded as commenced']),('Building Regulations: порядок',1,['T~BSR, The three gateways|Developers cannot proceed with construction until BSR has approved the application.'])],
('09-rabochaya','uk'):[('Что это',0,['R~Outcome: All design information required to manufacture and construct the project']),('Состав работ',0,['R~Stage 4 involves the preparation of all information required']),('Состав работ',1,['R~Specialist subcontractors’ design work should be allocated to Stage 4']),('Состав работ',2,['R~A Building Regulations Application should be made during Stage 4']),('Состав работ',3,['R~The Building Contract needs to be agreed and signed']),('Детализация',0,['R~Prescriptive Information can be used for construction purposes']),('Детализация',1,['R~It is not usually necessary to produce a Stage Report for Stage 4'])],
('10-stroitelstvo','uk'):[('Что это',0,['R~Outcome: Manufacturing, construction and Commissioning completed']),('Состав работ',0,['R~Stage 5 comprises the manufacturing and construction of the Building Systems']),('Состав работ',1,['R~It should be clear from the outset who is responsible for responding to Site Queries']),('Состав работ',2,['R~With the exception of resolving Site Queries, there is no design activity at Stage 5'])],
('11-ispolnitelnaya','uk'):[('Что это',0,['R~Preparations for handover will include compilation of the Building Manual']),('HRB',0,['T~BSR, The three gateways|For the completion certificate to be approved, there must be sufficient evidence to support that what was built reflects the approved plans, and the requirements of the building regulations have been met.'])],
('12-priemka-vvod','uk'):[('Что это',0,['R~Stage 5 concludes with the issue of a Practical Completion certificate']),('Completion certificate',1,['T~Building Regulations 2010, reg. 17|shall be evidence (but not conclusive evidence)']),('HRB: Gateway 3',0,['G~Only once Gateway Three has been passed can the new building be registered with BSR']),('HRB: Gateway 3',1,['T~BSR, The three gateways|The completion certificate application involves the submitted information forming the application - signed by the client, principal designer, and principal contractor - confirming that to the best of their knowledge, the HRB, as built, complies with all applicable requirements of the building regulations.'])],
('13-peredacha','uk'):[('Что это',0,['R~Outcome: Building handed over, Aftercare initiated and Building Contract concluded']),('Состав работ',0,['R~Usually twelve months after Practical Completion, the Final Certificate will be issued']),('Состав работ',1,['R~A Project Performance session needs be facilitated']),('Состав работ',2,['R~Post Occupancy Evaluation, conducted once any seasonal Commissioning has been completed'])],
('14-ekspluatatsiya','uk'):[('Что это',0,['R~Outcome: Building used, operated and maintained efficiently']),('Состав',0,['R~Post Occupancy Evaluation services are commissioned']),('Состав',1,['R~implementing Facilities Management or Asset Management strategies']),('Состав',2,['R~At the end of a building’s life, Stage 0 commences again'])],

# ---------------- ЕС
('01-strategiya','eu'):[('Что это',0,['A~divides the building project into six stages'])],
('02-zadanie','eu'):[('Что это',1,['A~The design phase will start with a review of the design brief']),('Пример Чехии',0,['C~The result of the Project Initiation should be a detailed program']),('Пример Чехии',1,['T~CKA, 2017 (Чехия)|additional services: Provide marketing plan; Provide feasibility study; Provide financial and economic analysis (of the building and its further operation)'])],
('03-koncepciya','eu'):[('Что это',0,['T~ACE, 2013, F8 (Франция)|Conceptual Design (esquisse) 1/200 & 1/500 except for the private house']),('Детализация',0,['T~ACE, 2013, F8 (Франция)|Conceptual Design (esquisse) 1/200 & 1/500 except for the private house']),('Детализация',1,['A~Each stage will culminate with set of plans']),('Пример Чехии',0,['C~A Concept Design (study) is the first graphic representation'])],
('04-eskiz','eu'):[('Что это',0,['T~ACE, 2013, F8 (Франция)|Preliminary Design (APS avant projet sommaire) 1/100 & 1/200; Preliminary Design (APD avant projet détaillé) 1/50 & 1/100']),('Детализация',0,['T~ACE, 2013, F8 (Франция)|Preliminary Design (APS avant projet sommaire) 1/100 & 1/200; Preliminary Design (APD avant projet détaillé) 1/50 & 1/100']),('Детализация',1,['A~You will have noticed that preliminary design is divided into two sub-stages']),('Пример Чехии',0,['C~Land Zone Permit Design is based on approved Concept Design'])],
('05-ago-agr','eu'):[('Аналог',0,['A~only the planning permission']),('Пример Чехии',0,['C~Land Zone Permit Design (the documents for issuance of a decree to locate a building)'])],
('06-proekt-razresheniya','eu'):[('Что это',0,['A~At the completion of the “Preliminary Design Stage”']),('Состав',1,['A~This additional material will include a written analysis']),('Состав',2,['A~Further statutory approvals may need to be sought']),('Пример Чехии',0,['C~The main purpose of the project for a Building Permit Design'])],
('07-ekspertiza','eu'):[('Что это',1,['A~Documents produced at this stage are reviewed by the technical controller'])],
('08-razreshenie','eu'):[('Что это',1,['A~Unless the scheme is located in a conservation area'])],
('09-rabochaya','eu'):[('Состав и детализация',0,['A~The developed design is the stage at which construction drawings are prepared']),('Состав и детализация',1,['A~Written specifications and a Bill of Quantities without quantities']),('Состав и детализация',2,['A~The architect will however provide an estimated cost breakdown']),('Состав и детализация',3,['A~the client may require that the architect provides construction or working drawings']),('Пример Чехии',0,['C~Detailed Design is designed in detail allowing to list construction works'])],
('10-stroitelstvo','eu'):[('Состав',0,['A~The architect will assemble the tender documentation']),('Состав',1,['A~In due course, the contract is agreed']),('Пример Чехии',0,['C~In this performance stage, the compiler of project documents checks'])],
('12-priemka-vvod','eu'):[('Пример Финляндии',0,['A~Building authorities would then conduct a final inspection'])],
('13-peredacha','eu'):[('Пример Чехии',0,['C~They assist the client during the takeover, snagging and possible reclamation procedures'])],

}
_IT="T~EN 16310 (по описанию iTeh)|"
for _slug,_k,_h,_i,_ref in [
 ('07-ekspertiza','eu','Что это',0,_IT+'Statutory Approval: “official license to build, to be issued by the local authorities, after determining compliancy of the design with applicable regulatory requirements.”'),
 ('08-razreshenie','eu','Что это',0,_IT+'Statutory Approval: “official license to build, to be issued by the local authorities, after determining compliancy of the design with applicable regulatory requirements.”'),
 ('13-peredacha','eu','Что это',0,_IT+'Handover: “step at which possession of the construction works is surrendered to the client upon completion with or without reservation.”'),
]:
    REFS.setdefault((_slug,_k),[]).append((_h,_i,[_ref]))
