# -*- coding: utf-8 -*-
# Ссылки на источники
L = dict(
 grk48='https://www.consultant.ru/document/cons_doc_LAW_51040/b884020ea7453099ba8bc9ca021b84982cadea7d/',
 grk49='https://www.consultant.ru/document/cons_doc_LAW_51040/4ca003dd6b793db91e6027babe790a482edd9b7e/',
 grk51='https://grkodeksrf.ru/gl-6/st-51-grk-rf', grk52='https://grkodeksrf.ru/gl-6/st-52-grk-rf',
 grk53='https://grkodeksrf.ru/gl-6/st-53-grk-rf', grk54='https://grkodeksrf.ru/gl-6/st-54-grk-rf',
 grk55='https://grkodeksrf.ru/gl-6/st-55-grk-rf', grk401='https://grkodeksrf.ru/gl-4/st-40-1-grk-rf',
 pp87='https://mchs.gov.ru/dokumenty/697', gost='https://meganorm.ru/Data2/1/4293720/4293720404.htm',
 mos='https://www.mos.ru/dgp/function/arkhitekturnaya-komissiya-po-rassmotreniyu-proektnykh-materialov/deyatelnost-arkhitekturnoi-komissii-po-rassmotreniyu-proektnykh-materialov/',
 rs='https://www.paragraf.rs/propisi/pravilnik-o-sadrzini-nacinu-i-postupku-izrade-i-nacinu-vrsenja-kontrole-tehnicke-dokumentacije-prema-klasi-i-nameni-objekata.html',
 rsold='https://www.paragraf.rs/propisi_download/pravilnik_o_sadrzini_nacinu_i_postupku_izrade_i_nacin_vrsenja_kontrole_tehnicke_dokumentacije_prema_klasi_i_nameni_objekata.pdf',
 zpi='https://www.paragraf.rs/propisi/zakon_o_planiranju_i_izgradnji.html',
 rs73='https://pravno-informacioni-sistem.rs/SlGlasnikPortal/eli/rep/sgrs/ministarstva/pravilnik/2019/73/1/reg',
 ace='https://oar.archi/wp-content/uploads/2021/03/the_design_and_construction_phases_of_a_construction_project_pdf_1478002177.pdf',
 iteh='https://standards.iteh.ai/catalog/standards/cen/7250e686-1a17-446c-bc6a-754708162070/en-16310-2013',
 riba='https://www.riba.org/media/syneeeto/2020ribaplanofworkoverviewpdf.pdf',
 bsa='https://www.thebesa.com/building-safety-act/gateways',
 cka='https://en.cka.cz/++api++/resources/standards-of-architects-scope-of-services.pdf/@@download/file',
 tcp='https://www.legislation.gov.uk/uksi/2015/595/article/34',
 br12='https://www.legislation.gov.uk/uksi/2010/2214/regulation/12', br16='https://www.legislation.gov.uk/uksi/2010/2214/regulation/16', br17='https://www.legislation.gov.uk/uksi/2010/2214/regulation/17',
 govbr='https://www.gov.uk/building-regulations-approval',
 gw='https://buildingsafety.campaign.gov.uk/wp-content/uploads/sites/157/2023/09/23_039-Building-Control-Authority-Booklet-3.pdf',
)
def a(t,k): return f'[{t}]({L[k]})'

SRC_RU48=a('ГрК РФ ст. 48','grk48'); SRC_RU49=a('ст. 49','grk49')
SRC_PP87=a('ПП РФ № 87','pp87'); SRC_GOST=a('ГОСТ Р 21.101-2020','gost')
SRC_RS=a('Правилник 96/2023','rs'); SRC_ZPI=a('Закон о планировании и строительстве','zpi')
SRC_ACE=a('отчёт ACE 2013','ace'); SRC_ITEH=a('EN 16310 (iTeh)','iteh'); SRC_RIBA=a('RIBA Plan of Work 2020','riba')
SRC_MOS=a('mos.ru/dgp','mos')

# Строки матрицы: (slug, название, {страна: (короткая ячейка, [ссылки])})
STAGES = [
 ('01-strategiya','Стратегия и обоснование',
  {'ru':('◐ практика: маркетинговое исследование, концепция девелопмента; нормативной стадии нет',[SRC_RU48]),
   'rs':('◐ *GNP* (генеральный проект), предварительное ТЭО, ТЭО',[a('Правилник чл. 2, 14, 34','rs'),a('Закон чл. 112–117','zpi')]),
   'eu':('≈ **0** Initiative',[SRC_ACE,SRC_ITEH]),
   'uk':('≈ **0** Strategic Definition',[SRC_RIBA])}),
 ('02-zadanie','Подготовка задания',
  {'ru':('◐ ТЗ на проектирование, ГПЗУ, ТУ, изыскания',[SRC_PP87+' п. 10',SRC_RU48+' ч. 11']),
   'rs':('◐ *lokacijski uslovi* — локационные условия (на основе IDR), срок 5 рабочих дней',[a('Закон чл. 53а, 55–56, 8д','zpi'),a('Правилник чл. 15','rs')]),
   'eu':('≈ **1** Initiation',[SRC_ACE,SRC_ITEH]),
   'uk':('≈ **1** Preparation and Briefing',[SRC_RIBA])}),
 ('03-koncepciya','Концепция',
  {'ru':('◐ АГК (практика Москвы)',[SRC_MOS]),
   'rs':('≈ *IDR* — идейное решение',[a('Правилник чл. 15, 35–41','rs'),a('Закон чл. 117а','zpi')]),
   'eu':('≈ **2.1** Conceptual Design',[SRC_ACE]),
   'uk':('≈ **2** Concept Design',[SRC_RIBA])}),
 ('04-eskiz','Эскиз / предварительный проект',
  {'ru':('◐ ЭП / ТЭО — практика, в ГрК нет',[SRC_RU48]),
   'rs':('≈ *IDP* — эскизный проект',[a('Правилник чл. 16, 42–49','rs'),a('Закон чл. 118','zpi')]),
   'eu':('≈ **2.2** Preliminary Design',[SRC_ACE]),
   'uk':('◐ **2** Concept Design (окончание)',[SRC_RIBA])}),
 ('05-ago-agr','Согласование архитектурного облика',
  {'ru':('🔸 АГО (федерально), в Москве АГР',[a('ГрК ст. 40.1','grk401'),a('ПП Москвы № 1423-ПП','mos')]),
   'rs':('—',[]),
   'eu':('— общей стадии нет; пример Чехии: *Land Zone Permit Design*',[a('CKA 2017','cka'),SRC_ACE]),
   'uk':('◐ planning permission: 8 недель (крупные — 13); для HRB Gateway 1',[SRC_RIBA,a('Order 2015, art. 34','tcp'),a('BSR','gw')])}),
 ('06-proekt-razresheniya','Проект для разрешения',
  {'ru':('≈ проектная документация (12 разделов)',[SRC_PP87,SRC_RU48]),
   'rs':('≈ *PGD* — проект для разрешения на строительство',[a('Правилник чл. 17, 51–57','rs'),a('Закон чл. 118а','zpi')]),
   'eu':('◐ **2.2–2.3**; пакет подаётся в конце Preliminary Design (пример Франции)',[SRC_ACE]),
   'uk':('◐ **3** Spatial Coordination; Planning Application в конце стадии',[SRC_RIBA])}),
 ('07-ekspertiza','Проверка / экспертиза проекта',
  {'ru':('🔸 экспертиза проектной документации и изысканий',[SRC_RU49]),
   'rs':('◐ *tehnička kontrola* PGD; *revizija* GNP и IDP',[a('Правилник чл. 79–86','rs'),a('Закон чл. 129, 131','zpi')]),
   'eu':('— (национальное право; пример Франции: technical controller)',[SRC_ACE]),
   'uk':('◐ Building Control (Full Plans / Building Notice); для HRB — Gateway 2 BSR до начала работ',[a('reg. 12','br12'),a('gov.uk','govbr'),a('BSR','gw')])}),
 ('08-razreshenie','Разрешение на строительство',
  {'ru':('≈ разрешение на строительство',[a('ГрК РФ ст. 51','grk51')]),
   'rs':('≈ *građevinska dozvola* — разрешение на строительство, срок 5 рабочих дней',[a('Закон чл. 135, 8д','zpi'),a('Правилник чл. 17','rs')]),
   'eu':('— *Statutory approval*: национальное право',[SRC_ITEH,SRC_ACE]),
   'uk':('◐ planning permission + Building Regulations (заявка на стадии 4; для HRB — Gateway 2)',[SRC_RIBA,a('reg. 16','br16')])}),
 ('09-rabochaya','Рабочая документация',
  {'ru':('≈ рабочая документация (РД)',[SRC_GOST+' п. 4.2',SRC_RU48]),
   'rs':('≈ *PZI* — проект для производства работ',[a('Правилник чл. 18, 61–70','rs'),a('Закон чл. 123','zpi')]),
   'eu':('≈ **2.3** Developed, **2.4** Technical Design/FEED, **2.5** Detailed Engineering',[SRC_ACE]),
   'uk':('≈ **4** Technical Design',[SRC_RIBA])}),
 ('10-stroitelstvo','Строительство',
  {'ru':('≈ строительство, стройконтроль, надзор (ГСН)',[a('ст. 52','grk52'),a('53','grk53'),a('54','grk54')]),
   'rs':('≈ *izvođenje radova* — *prijava radova* (уведомление о начале), *stručni nadzor*',[a('Закон чл. 148–153','zpi')]),
   'eu':('≈ **3** Procurement, **4.1–4.2** Pre-construction, Construction',[SRC_ACE]),
   'uk':('≈ **5** Manufacturing and Construction',[SRC_RIBA])}),
 ('11-ispolnitelnaya','Исполнительная документация',
  {'ru':('≈ исполнительная документация, акты освидетельствования',[a('ст. 52','grk52'),a('53','grk53')]),
   'rs':('≈ *PIO* — проект построенного объекта',[a('Правилник чл. 19, 71–78','rs'),a('Закон чл. 124','zpi')]),
   'eu':('— (⏳ не сверено)',[]),
   'uk':('◐ Verified Construction Information (стадия 5); для HRB — «золотая нить»',[SRC_RIBA,a('BSR','gw')])}),
 ('12-priemka-vvod','Приёмка и разрешение на ввод',
  {'ru':('≈ заключение о соответствии → разрешение на ввод',[a('ст. 54','grk54'),a('55','grk55')]),
   'rs':('≈ *tehnički pregled* → *upotrebna dozvola*, срок 5 рабочих дней',[a('Закон чл. 154–158','zpi')]),
   'eu':('◐ **4.3** Commissioning, **4.5** Regulatory approval',[SRC_ACE]),
   'uk':('◐ Practical Completion; completion certificate в течение 8 недель; для HRB — Gateway 3',[SRC_RIBA,a('reg. 17','br17'),a('BSR','gw')])}),
 ('13-peredacha','Передача заказчику',
  {'ru':('— (⏳ ГрК стадии не выделяет)',[]),
   'rs':('—',[]),
   'eu':('≈ **4.4** Hand over',[SRC_ACE]),
   'uk':('≈ **6** Handover',[SRC_RIBA])}),
 ('14-ekspluatatsiya','Эксплуатация',
  {'ru':('◐ отдельное регулирование (⏳)',[]),
   'rs':('◐ владелец обеспечивает содержание и осмотры объекта',[a('Закон чл. 159','zpi')]),
   'eu':('≈ **5** Usage, **6** End of life',[SRC_ACE]),
   'uk':('🔸 **7** Use (внутри плана работ)',[SRC_RIBA])}),
]
SRC_RS73=''
