# -*- coding: utf-8 -*-
import sys,os
sys.path.insert(0,os.path.dirname(__file__))
from qlib import Q,pair
L='https://www.legislation.gov.uk/'
SEC=[
('Закон о строительстве 1984 (Building Act 1984)','Закон — основа всей системы: он даёт право издавать строительные регламенты и определяет юридическую силу Approved Documents.',[L+'ukpga/1984/55/section/1',L+'ukpga/1984/55/section/6',L+'ukpga/1984/55/section/7'],[
 ('Building Act 1984, s. 1(1)',Q('ba1','(1) The appropriate national authority may, for any of the purposes of—','furthering the prevention or detection of crime,'),'Уполномоченный орган может издавать строительные регламенты в целях: (а) обеспечения здоровья, безопасности, благополучия и удобства людей в зданиях и вокруг них; (b) экономии топлива и энергии; (c) предотвращения расточительного расхода и загрязнения воды; (d) защиты или улучшения окружающей среды; (e) содействия устойчивому развитию; (f) предотвращения или раскрытия преступлений. (В тексте на сайте стоит пометка «E+W» — Англия и Уэльс.)'),
 ('Building Act 1984, s. 1(1A)',Q('ba1','(1A) Those matters are—','in connection with buildings.'),'Регламенты могут касаться: проектирования и строительства зданий, их сноса, услуг, оборудования и арматуры в зданиях.'),
 ('Building Act 1984, s. 6(1)',Q('ba6','(1) For the purpose of providing practical guidance with respect to the requirements of any provision of building regulations','suitable for that purpose.'),'Для практического руководства по требованиям регламентов уполномоченный орган (или назначенный им орган) может одобрить и выпустить любой документ либо одобрить документ, выпущенный иначе, если считает его подходящим. Так возникают Approved Documents.'),
 ('Building Act 1984, s. 7(1)',Q('ba7','(1) A failure on the part of a person to comply with an approved document','negative liability.'),'Несоблюдение Approved Document само по себе не влечёт гражданской или уголовной ответственности. Но если утверждается нарушение регламента, несоблюдение документа может использоваться как довод о виновности, а доказательство соблюдения — как довод против. То есть Approved Document — руководство, а не закон; другой путь допускается, если доказано соответствие регламенту.')]),
('Строительные регламенты 2010 (Building Regulations 2010)','Вторичное законодательство: общие требования (рег. 7) и «требования» приложения 1 (Part B — пожарная безопасность). Версия с поправками (в тексте сайта виден S.I. 2026/335).',[L+'uksi/2010/2214/regulation/7',L+'uksi/2010/2214/schedule/1'],[
 ('Building Regulations 2010, Schedule 1, B1',Q('brs1','B1 . The building shall be designed and constructed','at all material times.'),'B1: здание должно быть спроектировано и построено так, чтобы были предусмотрены надлежащие средства раннего оповещения о пожаре и надлежащие пути эвакуации из здания в безопасное место снаружи, пригодные для безопасного и эффективного использования во все существенные моменты.'),
 ('Building Regulations 2010, Schedule 1, B3(3)–(4)',Q('brs1','(3) Where reasonably necessary to inhibit the spread of fire within the building','within concealed spaces in its structure and fabric is inhibited.'),'B3(3)–(4): где это разумно необходимо, нужны меры, соразмерные размеру и назначению здания: деление огнестойкими конструкциями и/или автоматические установки подавления пожара; также должно ограничиваться скрытое распространение огня и дыма в скрытых полостях.'),
 ('Building Regulations 2010, Schedule 1, B4(1)',Q('brs1','B4 .—(1) The external walls of the building','height, use and position of the building.'),'B4(1): наружные стены должны надлежащим образом противостоять распространению огня по стенам и от здания к зданию с учётом высоты, назначения и положения здания.'),
 ('Building Regulations 2010, Schedule 1, B5',Q('brs1','B5 .—(1) The building shall be designed and constructed so as to provide reasonable facilities','gain access to the building.'),'B5: здание должно иметь разумные средства для помощи пожарным в защите жизни; на участке должны быть предусмотрены подъезды для пожарной техники.'),
 ('Building Regulations 2010, reg. 7(2) и 7(4)',Q('br7','(2) Subject to paragraph (3), building work shall be carried out so that materials which become part of an external wall','A2-s1, d0 or A1')+' … '+Q('br7','(4) In this regulation— (a) a “relevant building” means a building with a storey','contains one or more dwellings; (ii) contains an institution; or (iii) contains a room for residential purposes'),'Рег. 7(2): материалы наружной стены «relevant building» должны быть класса A2-s1,d0 или A1. Рег. 7(4): relevant building — здание с этажом на высоте не менее 18 м (без кровельных технических этажей), содержащее квартиры, учреждение или помещение для проживания. Это то же правило, что в AD B Vol 1, п. 10.14.')]),
('Регламент о процедурах для зданий повышенного риска (S.I. 2023/909)','The Building (Higher-Risk Buildings Procedures) (England) Regulations 2023 — «ворота» (gateways) для высотных жилых зданий: заявка на одобрение, сроки и документы.',[L+'uksi/2023/909/regulation/3',L+'uksi/2023/909/regulation/4',L+'uksi/2023/909/regulation/5',L+'uksi/2023/909/regulation/41'],[
 ('S.I. 2023/909, reg. 3',Q('hp3','3. Before any person starts HRB work','is to start in accordance with regulation 9(2)'),'Перед началом работ (или этапа) по зданию повышенного риска клиент должен: подать заявку на одобрение строительного контроля регулятору; получить одобрение; выполнить требования, которые по одобрению должны быть выполнены до начала; уведомить регулятора о дате начала (Gateway 2).'),
 ('S.I. 2023/909, reg. 4(2)(b)',Q('hp4','(b) (i) such other plans as necessary to show that the HRB work would comply','(viii) where the applicant proposes occupation of part of the building before completion of the HRB work, a partial completion strategy;'),'К заявке прилагаются планы, показывающие соответствие регламентам, а также: декларация о компетентности; план контроля строительства; план контроля изменений; план отчётности о происшествиях; заявление о соответствии строительным регламентам; файл по пожарной безопасности и аварийным ситуациям; при частичной эксплуатации до завершения — стратегия частичного завершения.'),
 ('S.I. 2023/909, reg. 5(1) — срок Gateway 2',Q('hp5','5. —(1) Where the regulator receives a building control approval application','agree in writing.'),'Если заявка действительна, регулятор уведомляет заявителя и рассматривает её в течение **12 недель** с даты получения (или дольше — по письменному соглашению). Срок подтверждён по первоисточнику.'),
 ('S.I. 2023/909, reg. 9(2)',Q('hp9','(2) At least five working days before the day on which the HRB work','that work is to start.'),'Не менее чем за пять рабочих дней до начала работ клиент уведомляет регулятора о намерении начать и дате начала.'),
 ('S.I. 2023/909, reg. 41(1) — срок Gateway 3',Q('hp41','41. —(1) Where the regulator receives a completion certificate application','agree in writing.'),'По заявке на сертификат о завершении (Gateway 3) регулятор определяет решение в течение **8 недель** с даты получения (или дольше — по письменному соглашению).'),
 ('S.I. 2023/909, reg. 44(1)',Q('hp44','44. —(1) The regulator must approve a completion certificate application','has been provided.'),'Регулятор одобряет заявку и выдаёт сертификат о завершении, если убедился, приняв все разумные меры, что работы завершены и соответствуют всем требованиям регламентов; документы и информация полны и точны; информация для передачи ответственному лицу предоставлена полностью.')]),
('Подача заявок на строительный контроль (Building Regulations 2010, рег. 12, 16, 17) и Gateway 1','Процедура для обычных (не HRB) зданий и планировочный «ворота» для высотных жилых зданий.',[L+'uksi/2010/2214/regulation/12',L+'uksi/2010/2214/regulation/16',L+'uksi/2010/2214/regulation/17',L+'uksi/2015/595/schedule/4'],[
 ('Building Regulations 2010, reg. 12(1)',Q('br12','12. —(1) This regulation applies to a person who intends to—','(d) make a material change of use.'),'Рег. 12 применяется к тому, кто намерен: вести строительные работы; заменять или обновлять тепловой элемент; менять энергетический статус здания; изменять назначение здания. Такие лица подают либо уведомление о работах (building notice), либо заявку на одобрение с полными планами.'),
 ('Building Regulations 2010, reg. 12(3)',Q('br12','(3) A person intending to carry out building work in relation to a building to which the Regulatory Reform (Fire Safety) Order 2005','full plans'),'Для зданий, на которые распространяется Указ о пожарной безопасности 2005 года (общественные, рабочие здания и др.), допустима только заявка с полными планами, а не простое уведомление о работах.'),
 ('Building Regulations 2010, reg. 16(1)',Q('br16','16. —(1) Subject to paragraphs (8) and (9), a person who proposes to carry out building work','day on which the notice was given.'),'Начинать работы можно, только подав органу уведомление о намерении начать и выдержав не менее двух дней после дня подачи уведомления.'),
 ('Building Regulations 2010, reg. 17(2)',Q('br17','(2) The specified period referred to in paragraph (1) is eight weeks','regulation 16(4)'),'Срок выдачи сертификата о завершении (для обычных зданий) — восемь недель с даты получения уведомления органом.'),
 ('Planning Order 2015, Schedule 4, прим. F9 (Gateway 1)',Q('dmpo4','Sch. 4 para. (zg): the words','(with reg. 5 )'),'Планировочный Gateway 1: для высотных жилых зданий до выдачи разрешения на планировку обязательна консультация по пожарной безопасности. В параграфе (zg) приложения 4 слова «Health and Safety Executive» заменены словами «Building Safety Regulator» с 27.01.2026 (S.I. 2026/20), то есть консультант теперь — отдельный регулятор.')]),
('Обязанности участников (Building Regulations 2010, Part 2A, рег. 11A, 11E, 11F)','Часть 2A введена 01.10.2023: обязанности заказчика, проектировщика и подрядчика, компетентность и проверка прошлых нарушений (для зданий повышенного риска).',[L+'uksi/2010/2214/regulation/11A',L+'uksi/2010/2214/regulation/11E',L+'uksi/2010/2214/regulation/11F'],[
 ('Building Regulations 2010, reg. 11A(1)–(2)',Q('br11a','11A. — (1) A client must make suitable arrangements for planning, managing and monitoring a project','whether it is higher-risk building work.'),'Заказчик должен организовать планирование, управление и контроль проекта (с достаточным временем и ресурсами) для соблюдения всех требований. Организация подходит, если: проектирование ведётся так, чтобы построенное здание соответствовало требованиям; работы ведутся в соответствии с ними; проектировщики и подрядчики сотрудничают; предусмотрены периодические проверки, не относится ли работа к строительству здания повышенного риска.'),
 ('Building Regulations 2010, reg. 11E(2)',Q('br11e','(2) Before permitting A to carry out any work—','(including any serious sanction).'),'Прежде чем допустить исполнителя к работе, заказчик (или назначающий) должен принять все разумные меры, чтобы убедиться в его компетентности; для зданий повышенного риска — спросить, не было ли в последние 5 лет серьёзных санкций, и учесть сведения о любом нарушении.'),
 ('Building Regulations 2010, reg. 11F(1)',Q('br11f','11F. — (1) Any person carrying out any building work or any design work must have—','if built, would be in accordance with all relevant requirements.'),'Любой исполнитель строительных или проектных работ должен обладать необходимыми навыками, знаниями, опытом и поведением (а организация — организационными возможностями), чтобы вести работы в соответствии со всеми требованиями и проектировать так, чтобы построенное соответствовало требованиям.')]),
('Эволюция Approved Document B: спринклеры в жилых домах (редакции 2006 → 2019)','Старая редакция (2006, Vol 2, п. 8.14) и текущая (2019 с поправками, Vol 1, п. 7.4). В 2006 Vol 1 относился только к индивидуальным домам; многоквартирные дома — Vol 2.',['https://www.gov.uk/government/publications/historical-documents-relating-to-approved-document-b-fire-safety','https://www.gov.uk/government/publications/fire-safety-approved-document-b'],[
 ('Approved Document B Vol 2 (2006), п. 8.14',Q('adb2_06','8.14 Blocks of flats with a floor more than 30m above ground level should be fitted with a sprinkler system','can be ignored.'),'Редакция 2006: спринклеры в блоках квартир — если этаж выше 30 м над землёй; только в квартирах, не в общих зонах; ограничение BS 9251 (до 20 м) можно игнорировать.'),
 ('Approved Document B Vol 1 (2019, с поправками), п. 7.4',Q('adb1','Blocks of flats with a top storey more than 11m above ground level','in accordance with Appendix E.'),'Текущая редакция: спринклеры — если верхний этаж выше 11 м; порог снижен с 30 м до 11 м. (Поправка введена после Гренфелла; точную дату и номер поправки в портале предстоит указать ⏳.)')]),
]
md=['---','hide:','  - toc','---','','# Англия: правовая основа (Building Act, Building Regulations, gateways)','',
'!!! warning "Статус: черновик"',
'    Тексты взяты с legislation.gov.uk (сохранённые страницы, версия «с изменениями на 06.10.2026»). Слева — оригинал, справа — рабочий перевод. Документы AD B и Building Bulletin 100 здесь не рассматриваются: их тексты — на gov.uk.','',
'Иерархия: **Building Act 1984** (закон) → **Building Regulations 2010** (регламент; требования Part B) → **Approved Documents** (руководство по соблюдению) → для высотных жилых зданий ещё **Building Safety Act 2022** и **S.I. 2023/275, 2023/909**.','']
for title,intro,links,ps in SEC:
    md+=[f'## {title}','',intro,'','Источники: '+'; '.join(f'[{u.split("gov.uk/",1)[1]}]({u})' for u in links),'']
    for lab,qt,ru in ps:
        md+=[l[4:] if l.startswith('    ') else l for l in pair(lab,qt,ru,'en')]
md+=['## Что осталось сверить','','- [ ] Текст параграфа (zg) приложения 4 к Planning Order 2015 (Gateway 1): прочитано только примечание об изменении консультанта.','- [ ] Эволюция AD B: даты введения поправок (2020, 2022, 2025–2029) и сравнение других разделов (фасады, лестницы).','- [ ] Reg. 11B–11D, 11G–11L и остальные положения Part 2A.','']
out='\n'.join(md)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','..','docs','normy','uk.md'),'w').write(out)
print(len(out))
